### PR TITLE
Add Logic to allow for the Kubernetes Validation Test to find Management IP for L2Bridge Networks

### PR DESCRIPTION
**Pull request by zawachte-msft**

### CODE REVIEW

**Comment by zawachte-msft** [comment]
@microsoft/containernet-msft  @ksubrmnn 

Turns out I don't have access to adding reviewers in this repo.

**Comment by ksubrmnn** [comment]
lgtm

**Comment by ksubrmnn** [comment]
@daschott Merge, please? :)

**Comment by JocelynBerrendonner** [comment]
LGTM

**Pull request merged**
