### PR TITLE
Initial commit for wincni source

### PR DESCRIPTION
**Pull request by JMesser81**
This provides a CNI plugin for Windows targeting the l2bridge HNS network driver. It requires static route configuration and manual HNS network creation

### CODE REVIEW

**Comment by feiskyer** [comment]
> It requires static route configuration and manual HNS network creation

maybe add a guide how to do this in readme?

**Comment by funky81** [comment]
Does this build solve problem where we can't ping to outside cluster from inside pod?

**Comment by aserdean** [comment]
/lgtm

Thanks for adding this!

Acked-by: Alin Gabriel Serdean <aserdean@ovn.org>

**Comment by alinbalutoiu** [comment]
Thanks for the PR!
/lgtm

**Pull request merged**
