### PR TITLE
Only using the kubelet flag `allow-privileged` for versions < 1.15

### PR DESCRIPTION
**Pull request by wk8**
Since that flag got deprecated in version 1.15, and the kubelet won't
start if it's present.

Fixes https://github.com/microsoft/SDN/issues/379

### CODE REVIEW

**Comment by dhirschfeld** [comment]
It would be great if this could be merged since 1.15 has been released a month ago.

I've always found it better to merge quickly and iterate. If there are new bugs they'll be fixed quickly due to the increased pace of development and they can't be worse than the current situation of being completely broken for k8s 1.15.

**Comment by dhirschfeld** [comment]
ping!

**Comment by szb640** [comment]
Any update on the pull request? Following the steps in the [Kubernetes' official guide](https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-nodes/#components-that-run-on-windows) are not working, but should:
 > Get the latest binaries from https://github.com/kubernetes/kubernetes/releases, starting with v1.14 or later

**Comment by wk8** [comment]
Maybe @madhanrm could take a look? :)

**Comment by madhanrm** [comment]
@daschott  can you take a look?

**Comment by daschott** [comment]
@madhanrm  Sure, I heard this is set in config file like the comment indicates. I will validate now.

**Comment by daschott** [comment]
LGTM, validated on 1.13 and 1.15. @madhanrm can you merge?

**Comment by wk8** [comment]
Thank you! :)

**Pull request merged**
