### PR TITLE
new cni bins

### PR DESCRIPTION
**Pull request by daschott**
New cni bins
 - K8s runtime env vars
 - HNS for IPAM (no IPAM needed)
 - bug fixes

### CODE REVIEW

**Comment by rhockenbury** [comment]
Where are these new binaries built from?  master @ https://github.com/containernetworking/plugins?  I seem to be having issues with node to service communication after deploying these.

**Comment by daschott** [comment]
@rhockenbury Node to service isn't supported on Windows: https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/common-problems#my-windows-node-cannot-access-my-services-using-the-service-ip

**Comment by rhockenbury** [comment]
Whoops.  Meant pod to service.  But only seems to be an issue on my test cluster running the 1.14 beta.  No issues on cluster running 1.13.1

**Comment by pjh** [comment]
+1 I'd also like to know the code what code these plugins were built from.

**Comment by daschott** [comment]
I should also add that this limitation of nodes not being able to access services should be overcome in Windows Server, version 1903.

The binaries in this PR are coming from Microsoft and any fixes will be upstreamed to containernetworking/plugins. There is a separate PR that @nagiesek will raise (the current one was just merged yesterday). In the interests of time the fixes have been pushed out here now so certain users are unblocked and conformance tests can refer to them. Unfortunately there is no plugins release on containernetworking/plugins of Windows plugins yet (though the next one should include Windows). We're actively working on improving the velocity of shipping new binaries in a more sustainable & transparent way and will update the community & any download instructions with that once ready.

**Comment by yujuhong** [comment]
> The binaries in this PR are coming from Microsoft and any fixes will be upstreamed to containernetworking/plugins. There is a separate PR that @nagiesek will raise (the current one was just merged yesterday). In the interests of time the fixes have been pushed out here now so certain users are unblocked and conformance tests can refer to them

@daschott I appreciate the quick fixes, but I still wish the process would be better... We don't know what fixes are included in these binaries, and it's hard to track what we are using in our environment (GCE). It'd help to have a summary for the fixes (or links to issues).

> We're actively working on improving the velocity of shipping new binaries in a more sustainable & transparent way and will update the community & any download instructions with that once ready.

Looking forward to that. Thanks!

**Comment by nagiesek** [comment]
built from here: https://github.com/nagiesek/plugins/tree/k8sDnsFix

**Comment by nagiesek** [comment]
Hi, these binaries are built from: https://github.com/nagiesek/plugins/tree/k8sDnsFix
They contain https://github.com/containernetworking/plugins/pull/215
As well as a commit added to use the k8s dns environment variables. I've done this in the mean time while we wait to discuss the proper dns approach with the Containernetworking/plugins folks

**Pull request merged**
